services:
  - type: web
    name: financor
    env: python
    buildCommand: pip install -r prestamos_app/requirements.txt
    startCommand: cd prestamos_app && PYTHONPATH=$PYTHONPATH:. gunicorn --bind=0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src/prestamos_app 
        