services:
  - type: web
    name: financor
    env: python
    buildCommand: pip install -r prestamos_app/requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: prestamos_app.app
      - key: FLASK_ENV
        value: production 